### ISSUE TITLE
Client.Status can't always parse time values

### ISSUE THREAD

**Issue by 3456091** [web3-storage/go-w3s-client#21]
I sporadically receive an error from Client.Status of "parsing time "" as "2006-01-02T15:04:05.999Z07:00": cannot parse "" as "2006") failed". Using the `w3` client with the same CID shows the top-level `created` field contains a valid date, but the date fields in the `deals` array are null.

**Comment by alanshaw** [comment]
Resolved by https://github.com/web3-storage/go-w3s-client/commit/0f7254abdb86c57f8e4def55069bfdff0710da3f
