### ISSUE TITLE
Is there any other Endpoint like api.web3.storage?

### ISSUE THREAD

**Issue by LiRiu** [web3-storage/go-w3s-client#24]
Is there any other Endpoint like api.web3.storage?
a list?

**Comment by LiRiu** [comment]
as a asian user.... the default endpoint [ api.web3.storage ] which over San Francisco is really far...
so that... the data transfer rate is very low...
is there a endpoint for asian user ?

**Comment by dchoi27** [comment]
So the API is hosted on Cloudflare, meaning that uploads should be going to a much closer API endpoint. However, our infra, even though it's globally distributed, is in fewer locations, which might explain issues with upload speeds.

In general, we're a few months out from a new uploads architecture that should make everything much faster.
