### ISSUE TITLE
Is go 1.18 not supported?

### ISSUE THREAD

**Issue by shaojunda** [web3-storage/go-w3s-client#26]
when I run the [Usage](https://github.com/web3-storage/go-w3s-client#usage) with go 1.18 I got those errors

```
# github.com/web3-storage/go-w3s-client/fs/adapter
../../../.gvm/pkgsets/go1.18/global/pkg/mod/github.com/web3-storage/go-w3s-client@v0.0.6/fs/adapter/unixfs.go:54:13: cannot use pathresolver.NewBasicResolver(unixFSFetcher) (value of type resolver.Resolver) as type *resolver.Resolver in struct literal:
	resolver.Resolver does not implement *resolver.Resolver (type *resolver.Resolver is pointer to interface, not interface)
../../../.gvm/pkgsets/go1.18/global/pkg/mod/github.com/web3-storage/go-w3s-client@v0.0.6/fs/adapter/unixfs.go:69:32: fs.resolver.ResolveToLastNode undefined (type *resolver.Resolver is pointer to interface, not interface)
```

**Comment by shaojunda** [comment]
solved by change go-path version from v0.3.0 to v0.2.1

**Comment by mattxyzeth** [comment]
@shaojunda can you explain how you solved this in more detail? How do I change my go-path version? Also, I'm not sure downgrading tooling is a reason to close this issue.

**Comment by mattxyzeth** [comment]
I'm dealing with the same error when I try to build my code on macos using go 1.18

**Comment by mattxyzeth** [comment]
Oh, I see. It's the github.com/ipfs/go-path module. Confirmed that downgrading that module to v0.2.1 prevents the error. Does anyone know why we can't use the v0.3.0 version of ipfs/go-path?
